<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://www.tum.de/factum/component" nsPrefix="org-tum-factum-component">
  <eClassifiers xsi:type="ecore:EClass" name="Pattern"/>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Interface"/>
  <eClassifiers xsi:type="ecore:EClass" name="PortType"/>
  <eClassifiers xsi:type="ecore:EClass" name="PortParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="InputPort"/>
  <eClassifiers xsi:type="ecore:EClass" name="OutputPort"/>
</ecore:EPackage>
